### ISSUE TITLE
Problem with "Rod" mount

### ISSUE THREAD

**Issue by rarroyo6** [MoonCactus/gopro_customizable_mounts#2]
When the Rod mount is rendered, the "hole" for the rod  sticks out rather than going inward.
Similar to the issue the tripod mount had. (Thanks for fixing that).

**Comment by MoonCactus** [comment]
Indeed, same problem (what the heck?) :D
Fixed - Thanks for testing, so I focus on fixing the bugs that should not exist in the first place ;)

**Comment by rarroyo6** [comment]
Thanks, I'm using it to mount some cameras flashes to my tripod and they fit perfectly.
By coincidence, I needed both the tripod mount and the rod mount. All's great now. :)

**Comment by MoonCactus** [comment]
Glad it suits you ! Actually it is the first time I get feedback for these specific mounts though this old design has ~100K views and 50K downloads on thingiverse (this is just amazing). I designed the rod mount specifically for versatile photo setups.
Would you be ok to send me a picture & allow me to add it on thingiverse or this wiki ? jeremie francois at gmail
